language: go

go:
  - 1.x

services:
  - docker

branches:
  only:
    - master

before_install:
  - openssl aes-256-cbc -K $encrypted_7ce11a41215f_key -iv $encrypted_7ce11a41215f_iv -in der-nackte-halloumi-api-travis.enc -out der-nackte-halloumi-api-travis -d

install: skip

script:
  - docker build -t dernacktehalloumi/api:${TRAVIS_BUILD_NUMBER} .
  - docker build -t dernacktehalloumi/migrations:${TRAVIS_BUILD_NUMBER} ./migrations
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then docker build -t dernacktehalloumi/api:latest .; fi
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then docker build -t dernacktehalloumi/migrations:latest ./migrations; fi

after_success:
  - bash scripts/docker_push.sh ${TRAVIS_BUILD_NUMBER}

deploy:
  skip_cleanup: true
  provider: script
  script: bash scripts/deploy.sh
  on:
    branch: master

notifications:
  email: false
