language: go

go:
  - 1.x

services:
  - docker

install: skip

script:
  # TODO: run tests
  - docker build -t dernacktehalloumi/api:${TRAVIS_BUILD_NUMBER} .
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then docker build -t dernacktehalloumi/api:latest .; fi'

after_success:
  - bash scripts/docker_push.sh ${TRAVIS_BUILD_NUMBER}

deploy:
  provider: script
  script:
    - bash scripts/docker_push.sh latest
    # TODO: trigger deploy application
  on:
    branch: master
