language: go

go:
  - 1.x

services:
  - docker

install: skip

script:
  # TODO: run tests
  - docker build -t dernacktehalloumi/api:${TRAVIS_BUILD_NUMBER} .
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then docker build -t dernacktehalloumi/api:latest .; fi'

after_success:
  # TODO: only push tagged image
  - bash scripts/docker_push.sh

deploy:
  provider: script
  script:
    # TODO: push latest image as well
    # TODO: trigger deploy application
  on:
    branch: master
